apiVersion: v1alpha1
kind: Setting
metadata:
  name: plugin-umami-settings
spec:
  forms:
    - group: basic
      label: 设置
      formSchema:
        - $formkit: text
          label: Umami 站点地址
          name: endpoint
          validation: required
        - $formkit: text
          label: 脚本名称
          name: scriptName
          validation: required
          value: umami.js
          help: Umami 1.x 默认为 umami.js，Umami 2.x 默认为 script.js
        - $formkit: text
          label: 站点 ID
          help: 即跟踪代码的 data-website-id
          name: websiteId
          validation: required
        - $formkit: text
          label: 共享链接
          name: url
          validation: required
          help: 可以在 Umami 的网站管理中获取共享链接
