apiVersion: plugin.halo.run/v1alpha1
kind: Plugin
metadata:
  name: PluginUmami
  annotations:
    "store.halo.run/app-id": "app-KfOps"
spec:
  enabled: true
  version: 1.0.0
  requires: ">=2.20.11"
  author:
    name: Halo
    website: https://github.com/halo-dev
  logo: logo.svg
  settingName: plugin-umami-settings
  configMapName: plugin-umami-configMap
  homepage: https://www.halo.run/store/apps/app-KfOps
  repo: https://github.com/halo-sigs/plugin-umami
  issues: https://github.com/halo-sigs/plugin-umami/issues
  displayName: "Umami"
  description: "提供对 Umami 的集成"
  pluginDependencies:
    PluginFeed?: ">=1.4.0"
  license:
    - name: "GPL-3.0"
      url: "https://github.com/halo-sigs/plugin-umami/blob/main/LICENSE"
